language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
# - osx
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
after_success:
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
